/*

Write an algorithm to determine if a number n is "happy".

A happy number is a number defined by the following process:

- Starting with any positive integer, replace the number by the sum of the
squares of its digits.
- Repeat the process until the number equals 1 (where it will stay), or it loops
endlessly in a cycle which does not include 1.
- Those numbers for which this process ends in 1 are happy.

Return true if n is a happy number, and false if not.

Example 1:
Input: n = 19

Output: true

Explanation:

1^2 + 9^2 = 82
8^2 + 2^2 = 68
6^2 + 8^2 = 100
1^2 + 0^2 + 0^2 = 1

Example 2:
Input: n = 2

Output: false

Constraints:
1 <= n <= 2^31 - 1

Approach:
1. We can use the Fast & Slow pointers approach to solve this problem.
2. The Fast & Slow pointers method is an efficient approach to find cycles in
the linked lists.
3. We can use the same approach to find a cycle among numbers generated by the
given function.
4. The algorithm is based on the idea that we can treat the number as a linked
list.
5. The getNext(n) function calculates the sum of the squares of the digits of
the number n.
6. The slow pointer moves one step at a time while the fast pointer moves two
steps at a time.
7. If the number is a happy number, the fast pointer will reach 1 before the
slow pointer.
8. If the number is not a happy number, the fast pointer will loop endlessly in
a cycle.
9. We can also use a hash set to keep track of all numbers generated by the
getNext(n) function.
10. If the number is a happy number, the fast pointer will reach 1 before the
number is repeated.
11. If the number is not a happy number, the number will be repeated before the
fast pointer reaches 1.
12. The time complexity of the algorithm is O(log n) and the space complexity is
O(1) or O(log n) depending on the approach used.



*/

#include <iostream>
#include <unordered_set>
using namespace std;

int getNext(int n) {
  
  int totalSum = 0;
  while (n > 0) {
    int digit = n % 10;
    n = n / 10;
    totalSum += digit * digit;
  }
  return totalSum;
}

// Fast & Slow pointer approach (Floyd's Cycle Detection)
// Both pointers start at n; fast moves two steps, slow moves one step per
// iteration. If the sequence reaches 1, it's a happy number. If slow == fast
// and neither is 1, a cycle was detected (not happy).
bool isHappy(int n) {
  int slow = n;
  int fast = n; // Bug fix: both pointers start at n
  do {
    slow = getNext(slow);          // slow moves 1 step
    fast = getNext(getNext(fast)); // fast moves 2 steps
  } while (fast != 1 && slow != fast);
  return fast == 1;
}

// Alternative approach: Hash Set to detect if the sequence cycles
// Space: O(log n)  |  Time: O(log n)
bool isHappyUsingSet(int n) { 
  unordered_set<int> seenNumbers;
  while (n != 1 && seenNumbers.find(n) == seenNumbers.end()) {
    seenNumbers.insert(n);
    n = getNext(n);
  }
  return n == 1;
}

int main() {
  int number;
  std::cout << "Enter a number: ";
  std::cin >> number;

  // Input validation: constraint is 1 <= n <= 2^31 - 1
  if (number < 1) {
    std::cout << "Invalid input. Please enter a positive integer." << std::endl;
    return 1;
  }

  // Approach 1: Fast & Slow pointer (Floyd's cycle detection) — O(1) space
  if (isHappy(number)) {
    std::cout << number << " is a happy number (Fast & Slow pointer)."
              << std::endl;
  } else {
    std::cout << number << " is not a happy number (Fast & Slow pointer)."
              << std::endl;
  }

  // Approach 2: Hash Set — O(log n) space
  if (isHappyUsingSet(number)) {
    std::cout << number << " is a happy number (Hash Set)." << std::endl;
  } else {
    std::cout << number << " is not a happy number (Hash Set)." << std::endl;
  }

  return 0;
}